### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by DanielaAndrade** [pinkeshbadjatiya/twitter-hatespeech#1]
Hi,

We are two Master Students writing our thesis on the topic of Hate Speech Detection. We were looking for a dataset and came across multiple papers who mention the annotated tweets dataset (Waseem, 2016). Unfortunately, most of the original tweet ids are no longer available for scrapping. We were wondering if you happened to have the data file with the original tweets, not just the ids. If so, we would kindly request if we could have access to it.

Thank you in advance,
Daniela and Kristin

**Comment by pinkeshbadjatiya** [comment]
Hi,
Good to hear that you are also working on this domain. Even we faced the same issue. Apparently, Waseem (2016) created the dataset and we received it from him. It would be better if you ask him for the dataset, I am sure he'll share it with you. Also, the Twitter Terms and Conditions do not allow sharing of scraped tweets, hence it won't be possible to share it publically with the code.
