### ISSUE TITLE
Commands Used for Paper and Problems while Running

### ISSUE THREAD

**Issue by paperHunts** [pinkeshbadjatiya/twitter-hatespeech#2]
Hi,

I found this repo from the paper "Deep Learning for Hate Speech Detection in Tweets" paper, but I cannot find the specific parameters that was used to get these results (ie. like what you have in the README with the Example commands). When running the code for cnn, lstm, and fast_text, I could not find the model that was supposed to be written out. Going over the code for cnn.py, lstm.py and fast_text.py I could not find the code snippet that would export the model for it to be used in nn_classifier.py.  There is a separate problem when trying to run the example BoWV, I get the following error:
>  BoWV.py: error: argument --tokenizer is required

In addition to this, what specific versions of your requirements (ie. Keras, SciKit) were used? When trying to run the code, I was getting errors/depreciation warnings until I found a version of scikit and keras that did not return such problems. I also had to figure out what version of Python was used. Would it be possible to update the README file with this information?

Thank you.

**Comment by pinkeshbadjatiya** [comment]
Hello,

Thanks for showing interest in our work. Let me address your queries one by one.
1. Regarding argument '--tokenizer', you need to provide the name of the tokenizer which you want to use. It has to be either of the two values "glove" or "nltk". I see the example command of BoWV.py did not specify the tokenizer. I might have missed it while pushing the code.
2. Regarding snippet to export the model: We intentionally skipped those snippets as we wanted all the individual models to work standalone and keep the code as clean as possible. For our experiments, you just need to create a pipeline that exports the model and then loads it. It should not require writing more than 5-10 additional lines.
3. Parameters for experiments: The example provides the closest parameters that we used for our experiments. You might need to do a few changes here and there. Also the number of possible combinations is also not too much so you can test with a few combinations. Most of the combinations can be skipped by simply looking at the results.
