### ISSUE TITLE
Troubles reproducing Part C classifiers from paper.

### ISSUE THREAD

**Issue by arnaudsj** [pinkeshbadjatiya/twitter-hatespeech#3]
Hi,

First of all, thank you for sharing your work. Very interesting results, and it is 10x better when the code is shared as well, so kudos to you!

I am interested in making a pull request based on the work I have already done to actualize the code base slightly (mostly for changes in API in latest version fo keras). However, I would like to get all the models running properly before I do so.

Currently, I appear to be missing something for the state of the art model which was presented in the paper (Part C) which seems to be implemented in nn_classifier.py.

It seems it requires embeddings/vocab generated in fasttext, but I am not finding anywhere in the code where those would be generated/saved to disk.
```
word2vec_model1 = np.load('fast_text.npy')
word2vec_model1 = word2vec_model1.reshape((word2vec_model1.shape[1], word2vec_model1.shape[2]))
f_vocab = open('vocab_fast_text', 'r')
```

Would you mind pointing me in the right direction on how to reproduce the following the Part C classifiers with the code provided? My initial scan through the code was not successful finding in particular random embeddings initialization, nor GBDT as the classifier.

- CNN+GloVe+GBDT
- CNN+Random Embedding+GBDT
- FastText+GloVe+GBDT
- FastText+Random Embedding+GBDT 
- LSTM+GloVe+GBDT
- LSTM+Random Embedding+GBDT

Thank you in advance!

**Comment by pinkeshbadjatiya** [comment]
We intentionally skipped those snippets that save the model to the disk as we wanted all the individual models to work standalone and keep the code as clean as possible. For our experiments, you just need to create a pipeline that exports the model and then loads it. It should not require writing more than 5-10 additional lines for saving/loading the model using standard API calls.

**Comment by thefirebanks** [comment]
Hello, 

We are 3 undergraduate students doing research on this topic and we are incredibly thankful to you for sharing the code. We were wondering if you could give us some details on how to output the model that is constructed by the NN_model.py (say, lstm.py). So far, we have tried to do:

IN lstm.py

model.save("filename.h5")

IN nn_classifier.py

f = h5py.File('weights.h5', 'r+')
data = f.get('/Documents/')
data_as_array = np.array(data)
np.save("model.npy", data_as_array)

word2vec_model1 = np.load("model.npy") #line 50 that was supposed to be modified 

But we are getting this error:

Traceback (most recent call last):
  File "nn_classifier.py", line 61, in <module>
    word2vec_model1 = word2vec_model1.reshape((word2vec_model1.shape[1], word2vec_model1.shape[2]))
IndexError: tuple index out of range

Is this not the right way to do it? Thank you so much in advance

**Comment by thefirebanks** [comment]
Hello,
We are 3 undergraduate students doing research on this topic and we are incredibly thankful to you for sharing the code. We were wondering if you could give us some details on how to output the model that is constructed by the NN_model.py (say, lstm.py). So far, we have stumbled upon many issues that we finally managed to solve, but we were not sure if this was the correct way of doing it. These are our attempt:

In lstm.py

#To store the model
model.save("LSTM.h5") 

#To store vocab
outfile = open("vocab_lstm.txt", 'w')
outfile.write(str(vocab))
outfile.close()

In nn_classifier.py

#Open model
f = h5py.File('LSTM.h5', 'r')
data = f['model_weights']['embedding_1']['embedding_1']['embeddings:0'][:]
np.save("model.npy", data)

#Load model
word2vec_model1 = np.load("model.npy")
word2vec_model1 = word2vec_model1.reshape((word2vec_model1.shape[0], word2vec_model1.shape[1]))

#Load vocab
f_vocab = open("vocab_lstm.txt", "r")
vocab_json = ast.literal_eval(f_vocab.read())

Also, we had to modify some lines to ensure that the encoding/decoding works, for example in lines 93 and 114 of nn_classifier.py we had to add

text = unicode(tweet['text'], errors='ignore')
words = glove_tokenize(text)

Is this the correct way of doing this? Thank you very much in advance.

**Comment by pinkeshbadjatiya** [comment]
Hello,

Sorry for late response, I was quite busy and forgot about this completely.
Glad you are interested in our work. Regarding the lines, all you have to do is save the model and the vocab and load them in the other model to complete the pipeline.

Regarding the above snippets, they seem fine to me, though I do not remember any tuple errors and reshaping. Just check again to make sure you are doing it right. Also, I am pretty sure you do not require handling the decoding errors, we remember handling them in our code. I will have to check again.
