### ISSUE TITLE
Out of vocabulary words

### ISSUE THREAD

**Issue by tuhinjubcse** [pinkeshbadjatiya/twitter-hatespeech#5]
Hi
Pinkesh

if my understanding is correct
text = ''.join([c for c in text if c not in punctuation]) 
should be
text = ' '.join([c for c in text if c not in punctuation])
check your lstm.py . Also I figured 3137 embedding missed  , I understand you are learning the weights of these words and it wouldnt matter , but did you try word segmentation like 
**outwiththecheats** should be **out with the cheats**
I believe these were hashtags

**Comment by pinkeshbadjatiya** [comment]
Yeah, `text = ' '.join([c for c in text if c not in punctuation])` is the correct one.
No, as mentioned in the paper, we did not try segmentation over the words or hashtags.
